In [1]:
from math import sqrt
import numpy as np

#### 1. Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks):

In [2]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
zp, ks

(array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110]),
 array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832]))

> 1. Найдите ковариацию этих двух величин с помощью элементарных действий, а затем с помощью функции cov из numpy
Полученные значения должны быть равны.
> 2. Найдите коэффициент корреляции Пирсона с помощью ковариации и среднеквадратичных отклонений двух признаков,
а затем с использованием функций из библиотек numpy и pandas.

In [3]:
# 1
cov_custom = (zp * ks).mean() - zp.mean() * ks.mean()
round(cov_custom, 2)

9157.84

In [4]:
np.cov(zp, ks, ddof=0)

array([[ 3494.64,  9157.84],
       [ 9157.84, 30468.89]])

In [5]:
# 2
corrcoef_custom = cov_custom / (zp.std() * ks.std())
corrcoef_custom

0.8874900920739158

In [6]:
np.corrcoef(zp, ks)[0, 1]

0.8874900920739162

#### 2. Измерены значения IQ выборки студентов, обучающихся в местных технических вузах:

In [7]:
stud_iq = np.array([131, 125, 115, 122, 131, 115, 107, 99, 125, 111])

> Известно, что в генеральной совокупности IQ распределен нормально. Найдите доверительный интервал для математического ожидания с надежностью 0.95

In [8]:
iq_selection_mean = stud_iq.mean()
iq_selection_mean

118.1

In [9]:
n = stud_iq.size
n

10

In [10]:
iq_selection_std = np.std(stud_iq, ddof=1)
iq_selection_std

10.54566788359614

In [11]:
t_from_table = 2.751  # для 2.5% (alpha = 5 / 2)

In [12]:
сonf_interval = t_from_table * iq_selection_std / n**0.5
сonf_interval

9.174125571955072

In [13]:
print(f'Доверительный интревал: ({iq_selection_mean - сonf_interval:.2f}\t{iq_selection_mean + сonf_interval:.2f})')

Доверительный интревал: (108.93	127.27)


#### 3. Известно, что рост футболистов в сборной распределен нормально с дисперсией генеральной совокупности, равной 25 кв.см. Объем выборки равен 27, среднее выборочное составляет 174.2

> Найдите доверительный интервал для математического ожидания с надежностью 0.95

In [14]:
X_mean = 174.2
football_std = sqrt(25)
n = 27

In [15]:
z_table = 1.96  # для 2.5% (alpha = 5 / 2)

In [16]:
сonf_interval = z_table * football_std / n**0.5
сonf_interval

1.8860108793527777

In [17]:
print(f'Доверительный интревал: ({X_mean - сonf_interval:.2f}\t{X_mean + сonf_interval:.2f})')

Доверительный интревал: (172.31	176.09)
